#!/bin/bash -x

set -e

for v in \
	   5.0.0~rc1 \
	   4.14.0 \
	   4.13.1 \
	   4.13.0 \
	   4.12.1 \
	   4.12.0 \
	   4.11.2 \
	   4.11.1 \
	   4.11.0 \
	   4.10.2 \
	   4.10.1 \
	   4.10.0 \
	     ;
    do
    echo "==== $v ===="
    tools/inopam $v tools/TRIP-TEST >& ~/tmp/TRIP-TEST-$v.log &
    done
wait
