#!/bin/bash -x

function noisy_error {
    echo "FAILED FAILED FAILED FAILED FAILED"
    exit 1
}

set -e
trap noisy_error ERR


echo "================ $OPAM_SWITCH_PREFIX ================"

#uncomment these when testing a new camlp5 release
#opam remove -y camlp5 || true
#opam install -y camlp5

(cd ../camlp5 && opam install -y .)
opam remove -y pa_ppx
opam pin remove -y pa_ppx
opam install -t -y --deps-only --working-dir .
opam install -t -y --working-dir .
